# Generated by Django 3.1.7 on 2021-03-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proformaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
