# Generated by Django 3.1.7 on 2021-04-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proformaApp', '0005_proforma_detalle_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='proforma',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='proforma_detalle',
            options={'ordering': ['-proforma']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-id']},
        ),
    ]
