# Generated by Django 3.1.7 on 2021-04-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proformaApp', '0006_auto_20210403_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id']},
        ),
    ]
