# Generated by Django 3.1.7 on 2021-04-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformaApp', '0003_remove_proforma_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=7),
            preserve_default=False,
        ),
    ]
